create table category (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(120) not null,
    description varchar(500) not null,
    image_path varchar(255) not null
);

create table product (
    id bigint generated by default as identity primary key,
    slug varchar(120) not null unique,
    name varchar(160) not null,
    description varchar(1000) not null,
    price numeric(10, 2) not null,
    discount_percentage integer not null default 0,
    stock integer not null,
    image_path varchar(255) not null,
    detail_image_path varchar(255) not null,
    active boolean not null default true,
    category_id bigint not null,
    constraint fk_product_category foreign key (category_id) references category (id)
);

create table user_account (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    email varchar(160) not null unique,
    full_name varchar(160) not null,
    password_hash varchar(120) not null,
    enabled boolean not null default true
);

create table user_role (
    user_account_id bigint not null,
    role varchar(40) not null,
    constraint pk_user_role primary key (user_account_id, role),
    constraint fk_user_role_account foreign key (user_account_id) references user_account (id)
);

create table store_event (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    venue varchar(120) not null,
    event_date date not null,
    event_time time not null,
    active boolean not null default true
);

create table promotion (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    description varchar(500) not null,
    product_name varchar(160) not null,
    highlight_color varchar(40) not null,
    starts_on date not null,
    ends_on date not null,
    active boolean not null default true
);

create table customer_order (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null,
    customer_name varchar(160) not null,
    email varchar(160) not null,
    address varchar(500) not null,
    payment_method varchar(80) not null,
    status varchar(40) not null,
    payment_status varchar(40) not null,
    total_amount numeric(10, 2) not null,
    created_at timestamp not null,
    constraint fk_customer_order_user foreign key (user_account_id) references user_account (id)
);

create table order_line (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    product_name varchar(160) not null,
    unit_price numeric(10, 2) not null,
    quantity integer not null,
    line_total numeric(10, 2) not null,
    constraint fk_order_line_order foreign key (order_id) references customer_order (id),
    constraint fk_order_line_product foreign key (product_id) references product (id)
);

create index idx_product_category on product (category_id);
create index idx_product_active on product (active);
create index idx_order_user_created on customer_order (user_account_id, created_at);
