create table audit_log (
    id bigint generated by default as identity primary key,
    actor varchar(80) not null,
    action varchar(80) not null,
    target_type varchar(80) not null,
    target_id bigint,
    detail varchar(500) not null,
    created_at timestamp not null
);

create index idx_audit_log_action_created on audit_log (action, created_at);
create index idx_audit_log_target on audit_log (target_type, target_id);
